# Generated by Django 4.0.2 on 2022-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipaBLOG', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
