# Generated by Django 4.0.2 on 2022-05-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipaBLOG', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publish_date']},
        ),
    ]
